import 'dart:convert';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<void> generateProposalPdf(Map<String, dynamic> data) async {
    final pdf = pw.Document();

    final title = data['title'] ?? 'Workshop Proposal';
    final desc = data['description'] ?? 'No description provided';
    final budget = (data['totalBudget'] ?? 0).toString();
    final participants = (data['expectedParticipants'] ?? 0).toString();
    
    // Decode signature if present
    Uint8List? sigBytes;
    if (data['signature'] != null) {
      sigBytes = base64Decode(data['signature']);
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Text('IEEE PES UTM - Workshop Wizard', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.green)),
                ),
                pw.SizedBox(height: 20),
                pw.Text('Proposal Title: $title', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Divider(),
                pw.SizedBox(height: 12),
                pw.Text('Budget: RM $budget'),
                pw.Text('Expected Participants: $participants'),
                pw.SizedBox(height: 20),
                pw.Text('Description:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(desc),
                pw.Spacer(),
                if (sigBytes != null) ...[
                  pw.Text('Authorized Signature:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 8),
                  pw.Image(pw.MemoryImage(sigBytes), height: 100),
                ],
                pw.SizedBox(height: 12),
                pw.Align(alignment: pw.Alignment.centerRight, child: pw.Text('Generated by Workshop Wizard © 2026', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey))),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save(), name: '$title.pdf');
  }
}
