# Workshop Wizard Mutations

# Upsert (update or insert) a user based on their auth.uid
mutation UpsertUser(
  $displayName: String!,
  $email: String!,
  $role: String!
) @auth(level: USER) {
  user_upsert(data: {
    id_expr: "auth.uid",
    displayName: $displayName,
    email: $email,
    role: $role
  })
}
