# Workshop Wizard Queries

# List all users
query ListUsers @auth(level: USER) {
  users {
    id
    displayName
    email
    role
  }
}

# Get current user profile
query GetCurrentUser @auth(level: USER) {
  user(key: { id_expr: "auth.uid" }) {
    id
    displayName
    email
    role
    bio
    contactNumber
  }
}
